tmp-save

diff --git a/n2n/scripts/build/00x0_n2n-bcopy.yml b/n2n/scripts/build/00x0_n2n-bcopy.yml
--- a/n2n/scripts/build/00x0_n2n-bcopy.yml
+++ b/n2n/scripts/build/00x0_n2n-bcopy.yml
@@ -1,4 +1,4 @@
-name: n2n-manual-build-publish
+name: n2n-init-version
 
 # This workflow uses actions that are not certified by GitHub.
 # They are provided by a third-party and are governed by
@@ -6,46 +6,28 @@ name: n2n-manual-build-publish
 # documentation.
 
 on:
-  # schedule:
-  #   - cron: "28 17 * * *"
-  push:
-    branches: ["master"]
-    # Publish semver tags as releases.
-    # tags: ["v*.*.*"]
-
-  pull_request:
-    branches: ["master"]
-
-  workflow_dispatch:
-    # secrets:
-    #       REGISTRY_USERNAME:
-    #         description: 'USERNAME for REGISTRY'
-    #         required: true
-    #       REGISTRY_TOKEN:
-    #         description: 'TOKEN for REGISTRY'
-    #         required: true
 
   workflow_call:
     inputs:
-      version_big:
+      VERSION_BIG:
         required: true
         description: "version_big e.g. v3 | v2"
-      version_small:
+      VERSION_SMALL:
         required: false
         description: "version_small e.g. 3.1.1 | 2.1.0"
-      version_commit:
+      VERSION_COMMIT:
         required: false
         description: "version_commit e.g. 1255 | 124"
-      version_b_s_rc:
+      VERSION_B_S_rC:
         required: true
         description: "version_b_s_rc e.g. v3 | v3_3.1.1_r1255"
-      str_os_archs:
+      STR_OS_ARCHS:
         required: true
         description: "str_os_archs e.g. linux/amd64"
-      str_download_urls:
+      STR_DOWNLOAD_URLS:
         required: true
         description: "str_download_urls e.g. https://raw.githubusercontent.com/lucktu/n2n/master/Linux/n2n_v3_linux_x64_v3.1.1_r1255_static_by_heiye.tar.gz"
-      force_push:
+      FORCE_PUSH:
         description: "force push to registry"
         required: true
         type: boolean
@@ -73,6 +55,7 @@ jobs:
       ONLY_BIGVERSION: ${{ steps.check-big-version-only.outputs.ONLY_BIGVERSION }}
       IS_LATEST_VERSION: ${{ steps.check-latest-version.outputs.IS_LATEST_VERSION }}
       NEED_FIX: ${{ steps.check-need-fix.outputs.NEED_FIX }}
+      BUILD_DOCKERFILE: ${{ steps.check-need-fix.outputs.BUILD_DOCKERFILE }}
       TEST_PLATFORM: ${{ steps.init-test-info.outputs.TEST_PLATFORM }}
 
     steps:
@@ -80,13 +63,29 @@ jobs:
         # depends on this library
         uses: actions/checkout@v3
 
-      - name: Check big version only
-        id: check-big-version-only
-        if: inputs.version_b_s_rc == inputs.version_big
+      - name: Check inputs
         run: |
           cd n2n
           PROJECT_ROOT_DIR=$(pwd)
           echo "n2n-scan-all - PROJECT_ROOT_DIR: ${PROJECT_ROOT_DIR}"
+          cd ./scripts/build
+          chmod +x *.sh
+          . 0x0_init_logger.sh.sh
+
+          LOG_INFO "VERSION_BIG: ${{ inputs.VERSION_BIG }}"
+          LOG_INFO "VERSION_SMALL: ${{ inputs.VERSION_SMALL }}"
+          LOG_INFO "VERSION_COMMIT: ${{ inputs.VERSION_COMMIT }}"
+          LOG_INFO "VERSION_B_S_rC: ${{ inputs.VERSION_B_S_rC }}"
+          LOG_INFO "STR_OS_ARCHS: ${{ inputs.STR_OS_ARCHS }}"
+          LOG_INFO "STR_DOWNLOAD_URLS: ${{ inputs.STR_DOWNLOAD_URLS }}"
+          LOG_INFO "FORCE_PUSH: ${{ inputs.FORCE_PUSH }}"
+
+
+      - name: Check big version only
+        id: check-big-version-only
+        if: inputs.VERSION_B_S_rC == inputs.VERSION_BIG
+        run: |
+          cd n2n
           cd ./scripts/build
           chmod +x *.sh
           . 0x0_init_logger.sh.sh
@@ -96,11 +95,9 @@ jobs:
 
       - name: Check latest version
         id: check-latest-version
-        if: inputs.version_b_s_rc == 'v3'
+        if: inputs.VERSION_B_S_rC == 'v3'
         run: |
           cd n2n
-          PROJECT_ROOT_DIR=$(pwd)
-          echo "n2n-scan-all - PROJECT_ROOT_DIR: ${PROJECT_ROOT_DIR}"
           cd ./scripts/build
           chmod +x *.sh
           . 0x0_init_logger.sh.sh
@@ -124,6 +121,10 @@ jobs:
             if [[ "${{ inputs.version_b_s_rc }}" == "${ned_libfix_versions_b_s_rc}" ]];then
               LOG_WARNING 需要修复 - ${BUILD_VERSION_B_S_rC}
               echo "NEED_FIX=true">> $GITHUB_OUTPUT
+
+              build_dockerfile=Dockerfile.build.debian-8
+              LOG_WARNING 使用 ${build_dockerfile} - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
+              echo "BUILD_DOCKERFILE=${build_dockerfile}">> $GITHUB_OUTPUT
               exit 0
             fi
           done
@@ -132,8 +133,6 @@ jobs:
         id: init-test-info
         run: |
           cd n2n
-          PROJECT_ROOT_DIR=$(pwd)
-          echo "n2n-scan-all - PROJECT_ROOT_DIR: ${PROJECT_ROOT_DIR}"
           cd ./scripts/build
           chmod +x *.sh
           . 0x0_init_logger.sh.sh
@@ -211,12 +210,10 @@ jobs:
               LOG_INFO "准备 编译/推送"
           fi
 
-  build-psuh-n2n_lucktu:
+  build-psuh-n2n:
     needs: [init-version, check-push]
     if: needs.check-push.outputs.SKIP_BUILD_PUSH != 'true'
     runs-on: ubuntu-latest
-    env:
-      APP_NAME: n2n_lucktu
     permissions:
       contents: read
       packages: write
@@ -234,9 +231,9 @@ jobs:
       # https://github.com/sigstore/cosign-installer
       - name: Install cosign
         if: github.event_name != 'pull_request'
-        uses: sigstore/cosign-installer@main
+        uses: sigstore/cosign-installer@v3.0.5
         with:
-          cosign-release: "v1.13.1"
+          cosign-release: 'v2.0.2' # optional
 
       # Workaround: https://github.com/docker/build-push-action/issues/461
       - name: Setup Docker buildx
@@ -252,16 +249,7 @@ jobs:
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_TOKEN }}
 
-      - name: Get Build Files
-        id: get-build-files
-        run: |
-          cd n2n
-          PROJECT_ROOT_DIR=$(pwd)
-          echo "n2n-scan-all - PROJECT_ROOT_DIR: ${PROJECT_ROOT_DIR}"
-          cd ./scripts/build
-          chmod +x *.sh
-          . 0x0_init_logger.sh.sh
-          mkdir -p 
+
 
       # Extract metadata (tags, labels) for Docker
       # https://github.com/docker/metadata-action
@@ -283,7 +271,7 @@ jobs:
         uses: docker/build-push-action@v3
         if: needs.init-version.outputs.NEED_FIX != 'true'
         with:
-          context: .
+          context: $${{ env.DOCKER_CONTEXT_PATH }}
           platforms: ${{ needs.init-version.outputs.TEST_PLATFORM }}
           load: true
           no-cache: true
@@ -292,26 +280,24 @@ jobs:
             VERSION_BIG=${{ inputs.version_big }}
             VERSION_SMALL=${{ inputs.version_small }}
             VERSION_COMMIT=${{ inputs.version_commit }}
-            VERSION_B_S_rC=${{ inputs.version_b_s_rc }}
+            VERSION_B_S_rC=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
             STR_DOWNLOAD_URLS=${{ inputs.str_download_urls }}
 
       - name: Test n2n
         id: n2n-test
         run: |
-          LOG_INFO() {
-              echo -e "\033[0;32m[INFO] $* \033[0m"
-          }
-          LOG_WARNING() {
-              echo -e "\033[0;33m[WARNING] $* \033[0m"
-          }
-          LOG_ERROR() {
-              echo -e "\033[0;31m[ERROR] $* \033[0m"
-          }
-          set -e
+          cd n2n
+          PROJECT_ROOT_DIR=$(pwd)
+          echo "n2n-scan-all - PROJECT_ROOT_DIR: ${PROJECT_ROOT_DIR}"
+          cd ./scripts/build
+          chmod +x *.sh
+          . 0x0_init_logger.sh.sh
+
           if [[ "${{ needs.init-version.outputs.NEED_FIX }}" == "true" ]];then
             LOG_WARNING 需要修复 - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
-            LOG_WARNING 使用 Dockerfile.debian-8 - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
-            echo "build_dockerfile=Dockerfile.debian-8">> $GITHUB_OUTPUT
+            build_dockerfile=Dockerfile.build.debian-8
+            LOG_WARNING 使用 ${build_dockerfile} - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
+            echo "build_dockerfile=${build_dockerfile}">> $GITHUB_OUTPUT
             exit 0
           fi
           LOG_WARNING "Test start: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
@@ -325,8 +311,9 @@ jobs:
               edge -h 2>&1 | xargs -I {} echo {})"
             if [[ -n "$(echo ${edge_result} | grep -E '(libcrypto.so.1.0.0)|(/lib/ld-linux.so.3)')" ]];then
               LOG_ERROR 出错了: ${edge_result}
-              LOG_WARNING 使用 Dockerfile.debian-8 - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
-              echo "build_dockerfile=Dockerfile.debian-8">> $GITHUB_OUTPUT
+            build_dockerfile=Dockerfile.build.debian-8
+            LOG_WARNING 使用 ${build_dockerfile} - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
+            echo "build_dockerfile=${build_dockerfile}">> $GITHUB_OUTPUT
               exit 0
             fi
             if [[ -z "$(echo ${edge_result,,} | grep welcome)" ]];then
@@ -346,11 +333,13 @@ jobs:
             docker run --rm \
               --platform ${test_platform} \
               ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:test \
-              supernode -h  || echo
+              supernode -h 2>&1 | echo || echo -e "\n# check supernode ignore errors"
             # LOG_WARNING "Test done - supernode"
           done
           LOG_WARNING "Test done: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
-          echo "build_dockerfile=Dockerfile">> $GITHUB_OUTPUT
+          build_dockerfile=Dockerfile.build.debian-stable
+          LOG_WARNING 使用 ${build_dockerfile} - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
+          echo "build_dockerfile=${build_dockerfile}">> $GITHUB_OUTPUT
           exit 0
 
       # Build and push Docker image with Buildx (don't push on PR)
@@ -359,7 +348,7 @@ jobs:
         id: build-and-push
         uses: docker/build-push-action@v3
         with:
-          context: .
+          context: $${{ env.DOCKER_CONTEXT_PATH }}
           file: ${{steps.n2n-test.outputs.build_dockerfile}}
           platforms: ${{ needs.init-version.outputs.BUILD_PLATFORMS }}
           push: ${{ github.event_name != 'pull_request' }}
@@ -369,24 +358,23 @@ jobs:
           cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:buildcache
           cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:buildcache,mode=max
           build-args: |
+            VERSION_BIG=${{ inputs.version_big }}
+            VERSION_SMALL=${{ inputs.version_small }}
+            VERSION_COMMIT=${{ inputs.version_commit }}
             VERSION_B_S_rC=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
-            BIG_VERSION=${{ needs.init-version.outputs.BUILD_BIG_VERSION }}
-            SMALL_VERSION=${{ needs.init-version.outputs.BUILD_SMALL_VERSION }}
-            COMMIT=${{ needs.init-version.outputs.BUILD_COMMIT }}
+            STR_DOWNLOAD_URLS=${{ inputs.str_download_urls }}
 
-      - name: Test n2n again
-        id: n2n-test-again
+
+      - name: Test n2n
+        id: n2n-test
         run: |
-          LOG_INFO() {
-              echo -e "\033[0;32m[INFO] $* \033[0m"
-          }
-          LOG_WARNING() {
-              echo -e "\033[0;33m[WARNING] $* \033[0m"
-          }
-          LOG_ERROR() {
-              echo -e "\033[0;31m[ERROR] $* \033[0m"
-          }
-          set -e
+          cd n2n
+          PROJECT_ROOT_DIR=$(pwd)
+          echo "n2n-scan-all - PROJECT_ROOT_DIR: ${PROJECT_ROOT_DIR}"
+          cd ./scripts/build
+          chmod +x *.sh
+          . 0x0_init_logger.sh.sh
+
           LOG_WARNING "Test start: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
           flag_test_pass="true"
           platforms=${{ needs.init-version.outputs.BUILD_PLATFORMS }}
@@ -395,7 +383,7 @@ jobs:
             LOG_WARNING "Test for platform: ${test_platform}"
             edge_result="$(docker run --rm \
               --platform ${test_platform} \
-              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
+              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.check-push.outputs.DOCKER_TAG }} \
               edge -h 2>&1 | xargs -I {} echo {})"
             if [[ -z "$(echo ${edge_result,,} | grep welcome)" ]];then
               LOG_ERROR 出错了: ${test_platform} - ${edge_result}
@@ -404,22 +392,22 @@ jobs:
             fi
             docker run --rm \
               --platform ${test_platform} \
-              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
+              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.check-push.outputs.DOCKER_TAG }} \
               ls /usr/local/sbin/edge
             docker run --rm \
               --platform ${test_platform} \
-              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
-              edge -h
+              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.check-push.outputs.DOCKER_TAG }} \
+              edge -h 2>&1 | xargs -I {} echo {}
             LOG_WARNING "Test pass - edge"
             docker run --rm \
               --platform ${test_platform} \
-              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
+              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.check-push.outputs.DOCKER_TAG }} \
               ls /usr/local/sbin/supernode
             # supernode will not pass
             docker run --rm \
               --platform ${test_platform} \
-              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
-              supernode -h  || echo
+              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.check-push.outputs.DOCKER_TAG }} \
+              supernode -h 2>&1 | xargs -I {} echo {} || echo
             # LOG_WARNING "Test done - supernode"
           done
           if [[ "${flag_test_pass}" != "true" ]];then
